// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: _.proto
/* eslint-disable */

import * as _P from "@3-/protoscript";

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const STATE_OK = 0;
export const STATE_JSON = 1;
export const STATE_CODE = 2;
export const STATE_NEED_SIGNIN = 3;
export const STATE_CAPTCHA = 4;
export const STATE_NO_PERMISSION = 5;
export const STATE_MISS_FUNC = 100;
export const STATE_ARGS_INVALID = 101;
export const STATE_BATCH_LIMIT = 102;
export const STATE_CALL_ERROR = 103;

/**
 * Serializes CallLi to protobuf.
 */
export const CallLiEncode = (msg) =>
  _P.getResultBuffer(CallLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CallLi from protobuf.
 */
export const CallLiDecode = (bytes) =>
  CallLiRead(CallLiNew(), _P.binaryReader(bytes));
const CallLiNew = () => [[], []];
const CallLiWrite = _P.encoder(_P.writePackedUint32, _P.writeRepeatedBytes);
const CallLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        if (_P.isDelimited(reader)) {
          msg[0].push(..._P.readPackedUint32(reader));
        } else {
          msg[0].push(_P.readUint32(reader));
        }
        break;
      }
      case 2: {
        msg[1].push(_P.readBytes(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes BinLi to protobuf.
 */
export const BinLiEncode = (msg) =>
  _P.getResultBuffer(BinLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes BinLi from protobuf.
 */
export const BinLiDecode = (bytes) =>
  BinLiRead(BinLiNew(), _P.binaryReader(bytes));
const BinLiNew = () => [[], []];
const BinLiWrite = _P.encoder(_P.writePackedUint32, _P.writeRepeatedBytes);
const BinLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        if (_P.isDelimited(reader)) {
          msg[0].push(..._P.readPackedUint32(reader));
        } else {
          msg[0].push(_P.readUint32(reader));
        }
        break;
      }
      case 2: {
        msg[1].push(_P.readBytes(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes Code to protobuf.
 */
export const CodeEncode = (msg) =>
  _P.getResultBuffer(CodeWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Code from protobuf.
 */
export const CodeDecode = (bytes) =>
  CodeRead(CodeNew(), _P.binaryReader(bytes));
const CodeNew = () => 0;
const CodeWrite = _P.encoder1(_P.writeUint32);
const CodeRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg = _P.readUint32(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes Json to protobuf.
 */
export const JsonEncode = (msg) =>
  _P.getResultBuffer(JsonWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Json from protobuf.
 */
export const JsonDecode = (bytes) =>
  JsonRead(JsonNew(), _P.binaryReader(bytes));
const JsonNew = () => "";
const JsonWrite = _P.encoder1(_P.writeString);
const JsonRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg = _P.readString(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
