// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: _.proto
/* eslint-disable */

import * as _P from "@3-/protoscript";

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

/**
 * Serializes Call to protobuf.
 */
export const CallEncode = (msg) =>
  _P.getResultBuffer(CallWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Call from protobuf.
 */
export const CallDecode = (bytes) =>
  CallRead(CallNew(), _P.binaryReader(bytes));
const CallNew = () => [0, _P.EMPTY_BIN];
const CallWrite = _P.encoder(_P.writeInt32, _P.writeBytes);
const CallRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readInt32(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes CallLi to protobuf.
 */
export const CallLiEncode = (msg) =>
  _P.getResultBuffer(CallLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CallLi from protobuf.
 */
export const CallLiDecode = (bytes) =>
  CallLiRead(CallLiNew(), _P.binaryReader(bytes));
const CallLiNew = () => [[], []];
const CallLiWrite = _P.encoder(_P.writePackedInt32, _P.writeRepeatedBytes);
const CallLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        if (_P.isDelimited(reader)) {
          msg[0].push(..._P.readPackedInt32(reader));
        } else {
          msg[0].push(_P.readInt32(reader));
        }
        break;
      }
      case 2: {
        msg[1].push(_P.readBytes(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes BinLi to protobuf.
 */
export const BinLiEncode = (msg) =>
  _P.getResultBuffer(BinLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes BinLi from protobuf.
 */
export const BinLiDecode = (bytes) =>
  BinLiRead(BinLiNew(), _P.binaryReader(bytes));
const BinLiNew = () => [];
const BinLiWrite = _P.encoder1(_P.writeRepeatedBytes);
const BinLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg.push(_P.readBytes(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes CodeBin to protobuf.
 */
export const CodeBinEncode = (msg) =>
  _P.getResultBuffer(CodeBinWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CodeBin from protobuf.
 */
export const CodeBinDecode = (bytes) =>
  CodeBinRead(CodeBinNew(), _P.binaryReader(bytes));
const CodeBinNew = () => [0, _P.EMPTY_BIN];
const CodeBinWrite = _P.encoder(_P.writeUint32, _P.writeBytes);
const CodeBinRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readUint32(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes Code to protobuf.
 */
export const CodeEncode = (msg) =>
  _P.getResultBuffer(CodeWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Code from protobuf.
 */
export const CodeDecode = (bytes) =>
  CodeRead(CodeNew(), _P.binaryReader(bytes));
const CodeNew = () => 0;
const CodeWrite = _P.encoder1(_P.writeUint32);
const CodeRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg = _P.readUint32(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes CodeLi to protobuf.
 */
export const CodeLiEncode = (msg) =>
  _P.getResultBuffer(CodeLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CodeLi from protobuf.
 */
export const CodeLiDecode = (bytes) =>
  CodeLiRead(CodeLiNew(), _P.binaryReader(bytes));
const CodeLiNew = () => [];
const CodeLiWrite = _P.encoder1(_P.writePackedUint32);
const CodeLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        if (_P.isDelimited(reader)) {
          msg.push(..._P.readPackedUint32(reader));
        } else {
          msg.push(_P.readUint32(reader));
        }
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes CodeMsgLi to protobuf.
 */
export const CodeMsgLiEncode = (msg) =>
  _P.getResultBuffer(CodeMsgLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CodeMsgLi from protobuf.
 */
export const CodeMsgLiDecode = (bytes) =>
  CodeMsgLiRead(CodeMsgLiNew(), _P.binaryReader(bytes));
const CodeMsgLiNew = () => [[], []];
const CodeMsgLiWrite = _P.encoder(_P.writePackedUint32, _P.writeRepeatedString);
const CodeMsgLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        if (_P.isDelimited(reader)) {
          msg[0].push(..._P.readPackedUint32(reader));
        } else {
          msg[0].push(_P.readUint32(reader));
        }
        break;
      }
      case 2: {
        msg[1].push(_P.readString(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes Captcha to protobuf.
 */
export const CaptchaEncode = (msg) =>
  _P.getResultBuffer(CaptchaWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Captcha from protobuf.
 */
export const CaptchaDecode = (bytes) =>
  CaptchaRead(CaptchaNew(), _P.binaryReader(bytes));
const CaptchaNew = () => [_P.EMPTY_BIN, _P.EMPTY_BIN, _P.EMPTY_BIN];
const CaptchaWrite = _P.encoder(_P.writeBytes, _P.writeBytes, _P.writeBytes);
const CaptchaRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readBytes(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      case 3: {
        msg[2] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
