// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: _.proto
/* eslint-disable */

import * as _P from "@3-/protoscript";

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const ERR_CODE_USER = 0;
export const ERR_CODE_CAPTCHA = 1;
export const ERR_CODE_FORM = 2;

/**
 * Serializes Call to protobuf.
 */
export const CallEncode = (msg) =>
  _P.getResultBuffer(CallWrite(msg, _P.binaryWriter()));
/**
 * Deserializes Call from protobuf.
 */
export const CallDecode = (bytes) =>
  CallRead(CallNew(), _P.binaryReader(bytes));
const CallNew = () => [0, _P.EMPTY_BIN];
const CallWrite = _P.encoder(_P.writeInt32, _P.writeBytes);
const CallRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readInt32(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes CallLi to protobuf.
 */
export const CallLiEncode = (msg) =>
  _P.getResultBuffer(CallLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes CallLi from protobuf.
 */
export const CallLiDecode = (bytes) =>
  CallLiRead(CallLiNew(), _P.binaryReader(bytes));
const CallLiNew = () => [];
const CallLiWrite = _P.encoder1(_P.writeRepeatedMessage(CallWrite));
const CallLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        const m = CallNew();
        _P.readMessage(reader, m, CallRead);
        msg.push(m);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes BinLi to protobuf.
 */
export const BinLiEncode = (msg) =>
  _P.getResultBuffer(BinLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes BinLi from protobuf.
 */
export const BinLiDecode = (bytes) =>
  BinLiRead(BinLiNew(), _P.binaryReader(bytes));
const BinLiNew = () => [];
const BinLiWrite = _P.encoder1(_P.writeRepeatedBytes);
const BinLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg.push(_P.readBytes(reader));
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes FormErr to protobuf.
 */
export const FormErrEncode = (msg) =>
  _P.getResultBuffer(FormErrWrite(msg, _P.binaryWriter()));
/**
 * Deserializes FormErr from protobuf.
 */
export const FormErrDecode = (bytes) =>
  FormErrRead(FormErrNew(), _P.binaryReader(bytes));
const FormErrNew = () => [0];
const FormErrWrite = _P.encoder(_P.writeUint32, _P.writeBytes);
const FormErrRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readUint32(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes FormErrLi to protobuf.
 */
export const FormErrLiEncode = (msg) =>
  _P.getResultBuffer(FormErrLiWrite(msg, _P.binaryWriter()));
/**
 * Deserializes FormErrLi from protobuf.
 */
export const FormErrLiDecode = (bytes) =>
  FormErrLiRead(FormErrLiNew(), _P.binaryReader(bytes));
const FormErrLiNew = () => [];
const FormErrLiWrite = _P.encoder1(_P.writeRepeatedMessage(FormErrWrite));
const FormErrLiRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        const m = FormErrNew();
        _P.readMessage(reader, m, FormErrRead);
        msg.push(m);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
/**
 * Serializes ErrMsg to protobuf.
 */
export const ErrMsgEncode = (msg) =>
  _P.getResultBuffer(ErrMsgWrite(msg, _P.binaryWriter()));
/**
 * Deserializes ErrMsg from protobuf.
 */
export const ErrMsgDecode = (bytes) =>
  ErrMsgRead(ErrMsgNew(), _P.binaryReader(bytes));
const ErrMsgNew = () => [0, _P.EMPTY_BIN];
const ErrMsgWrite = _P.encoder(_P.writeEnum, _P.writeBytes);
const ErrMsgRead = (msg, reader) => {
  while (_P.nextField(reader)) {
    switch (_P.getFieldNumber(reader)) {
      case 1: {
        msg[0] = _P.readEnum(reader);
        break;
      }
      case 2: {
        msg[1] = _P.readBytes(reader);
        break;
      }
      default: {
        _P.skipField(reader);
        break;
      }
    }
  }
  return msg;
};
